/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\work\\webBook\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2f266195",
    path: "/backend/arthas.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f266195").then(next)
    },
  },
  {
    name: "v-5cae44f9",
    path: "/backend/hadoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cae44f9").then(next)
    },
  },
  {
    name: "v-7a4279ad",
    path: "/backend/fdfs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a4279ad").then(next)
    },
  },
  {
    name: "v-0e35b1e6",
    path: "/backend/easyexcel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e35b1e6").then(next)
    },
  },
  {
    name: "v-47421376",
    path: "/backend/springboot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47421376").then(next)
    },
  },
  {
    name: "v-738904cd",
    path: "/backend/logback.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-738904cd").then(next)
    },
  },
  {
    name: "v-0c38dd66",
    path: "/backend/problem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c38dd66").then(next)
    },
  },
  {
    name: "v-9d4796fc",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d4796fc").then(next)
    },
  },
  {
    name: "v-37bad3a1",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37bad3a1").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6e005e12",
    path: "/backend/threadpool.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e005e12").then(next)
    },
  },
  {
    name: "v-47f2f04d",
    path: "/backend/intelij.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47f2f04d").then(next)
    },
  },
  {
    name: "v-4d8f3ed2",
    path: "/front/html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d8f3ed2").then(next)
    },
  },
  {
    name: "v-72575465",
    path: "/other/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72575465").then(next)
    },
  },
  {
    name: "v-f3113d26",
    path: "/front/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3113d26").then(next)
    },
  },
  {
    name: "v-0113b22d",
    path: "/front/nvm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0113b22d").then(next)
    },
  },
  {
    name: "v-2962c509",
    path: "/yunwei/gitbook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2962c509").then(next)
    },
  },
  {
    name: "v-3dfff727",
    path: "/yunwei/gitlab.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3dfff727").then(next)
    },
  },
  {
    name: "v-0d62e08d",
    path: "/front/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d62e08d").then(next)
    },
  },
  {
    name: "v-3f593db4",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f593db4").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-20aeff4b",
    path: "/yunwei/nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20aeff4b").then(next)
    },
  },
  {
    name: "v-795cf747",
    path: "/yunwei/rabbitmq.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-795cf747").then(next)
    },
  },
  {
    name: "v-0e55c647",
    path: "/yunwei/prometheus.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e55c647").then(next)
    },
  },
  {
    name: "v-40e88cda",
    path: "/yunwei/jenkins.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40e88cda").then(next)
    },
  },
  {
    name: "v-9f72326e",
    path: "/yunwei/redis.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f72326e").then(next)
    },
  },
  {
    name: "v-2a9f0bcb",
    path: "/yunwei/vim.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a9f0bcb").then(next)
    },
  },
  {
    name: "v-5b312dd2",
    path: "/yunwei/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b312dd2").then(next)
    },
  },
  {
    name: "v-46e46387",
    path: "/yunwei/supervisor.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46e46387").then(next)
    },
  },
  {
    name: "v-31d05c87",
    path: "/yunwei/wiki.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31d05c87").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]