/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "山雨光云的技术手册",
  "description": "山雨光云的技术手册",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/work.png",
        "heroText": "山雨光云的技术手册",
        "tagline": "前后端、运维技术手册",
        "actionText": "打开笔记 →",
        "actionLink": "/front/vue",
        "features": [
          {
            "title": "前端",
            "details": "Html、Css、JavaScript、Vue相关技术栈"
          },
          {
            "title": "后端",
            "details": "Java、SpringBoot、SpringCloud、Mysql、Redis等相关技术栈，尤其擅长多线程相关技术"
          },
          {
            "title": "运维",
            "details": "包含Gitlab、Jenkins、FDFS、Nginx等基础服务搭建及脚本"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a94b7e40",
      "path": "/"
    },
    {
      "title": "Arthas",
      "frontmatter": {},
      "regularPath": "/backend/arthas.html",
      "relativePath": "backend/arthas.md",
      "key": "v-9888b614",
      "path": "/backend/arthas.html",
      "headers": [
        {
          "level": 2,
          "title": "热修复",
          "slug": "热修复"
        },
        {
          "level": 2,
          "title": "查看线上运行代码",
          "slug": "查看线上运行代码"
        }
      ]
    },
    {
      "title": "Canal同步mysql到ES",
      "frontmatter": {},
      "regularPath": "/backend/canal.html",
      "relativePath": "backend/canal.md",
      "key": "v-583735ee",
      "path": "/backend/canal.html",
      "headers": [
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 2,
          "title": "选用canal做数据同步",
          "slug": "选用canal做数据同步"
        },
        {
          "level": 3,
          "title": "1.开启mysql的binlog(自建，阿里云上的默认开启)",
          "slug": "_1-开启mysql的binlog-自建-阿里云上的默认开启"
        },
        {
          "level": 3,
          "title": "2.下载canal相关组件，我用的1.1.3",
          "slug": "_2-下载canal相关组件-我用的1-1-3"
        }
      ]
    },
    {
      "title": "EasyExcel使用",
      "frontmatter": {},
      "regularPath": "/backend/easyexcel.html",
      "relativePath": "backend/easyexcel.md",
      "key": "v-46789dae",
      "path": "/backend/easyexcel.html",
      "headers": [
        {
          "level": 2,
          "title": "导出复杂表头",
          "slug": "导出复杂表头"
        },
        {
          "level": 2,
          "title": "最后使用合计行",
          "slug": "最后使用合计行"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        }
      ]
    },
    {
      "title": "Elasticsearch",
      "frontmatter": {},
      "regularPath": "/backend/elasticsearch.html",
      "relativePath": "backend/elasticsearch.md",
      "key": "v-7e715fae",
      "path": "/backend/elasticsearch.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "启动",
          "slug": "启动"
        },
        {
          "level": 3,
          "title": "新建用户",
          "slug": "新建用户"
        },
        {
          "level": 3,
          "title": "修改ip",
          "slug": "修改ip"
        },
        {
          "level": 3,
          "title": "文件数过小",
          "slug": "文件数过小"
        },
        {
          "level": 2,
          "title": "分词器",
          "slug": "分词器"
        },
        {
          "level": 2,
          "title": "Kibana安装",
          "slug": "kibana安装"
        },
        {
          "level": 2,
          "title": "ES基本概念",
          "slug": "es基本概念"
        }
      ]
    },
    {
      "title": "FDFS使用",
      "frontmatter": {},
      "regularPath": "/backend/fdfs.html",
      "relativePath": "backend/fdfs.md",
      "key": "v-11fa958e",
      "path": "/backend/fdfs.html",
      "headers": [
        {
          "level": 2,
          "title": "是什么",
          "slug": "是什么"
        },
        {
          "level": 2,
          "title": "FDFS搭建",
          "slug": "fdfs搭建"
        },
        {
          "level": 2,
          "title": "FDFS使用",
          "slug": "fdfs使用-2"
        }
      ]
    },
    {
      "title": "Flink-CDC同步Oracle全量+增量数据",
      "frontmatter": {},
      "regularPath": "/backend/flinkcdc.html",
      "relativePath": "backend/flinkcdc.md",
      "key": "v-7fc33a60",
      "path": "/backend/flinkcdc.html",
      "headers": [
        {
          "level": 2,
          "title": "Docker安装Oracle11g",
          "slug": "docker安装oracle11g"
        },
        {
          "level": 2,
          "title": "Oracle操作",
          "slug": "oracle操作"
        },
        {
          "level": 3,
          "title": "程序开发",
          "slug": "程序开发"
        }
      ]
    },
    {
      "title": "Hadoop",
      "frontmatter": {},
      "regularPath": "/backend/hadoop.html",
      "relativePath": "backend/hadoop.md",
      "key": "v-3d78ef4c",
      "path": "/backend/hadoop.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        }
      ]
    },
    {
      "title": "Intelij一些设置",
      "frontmatter": {},
      "regularPath": "/backend/intelij.html",
      "relativePath": "backend/intelij.md",
      "key": "v-07764124",
      "path": "/backend/intelij.html",
      "headers": [
        {
          "level": 2,
          "title": "注释模版",
          "slug": "注释模版"
        },
        {
          "level": 3,
          "title": "类注释模版",
          "slug": "类注释模版"
        },
        {
          "level": 3,
          "title": "方法注释模版",
          "slug": "方法注释模版"
        }
      ]
    },
    {
      "title": "Kafka相关命令",
      "frontmatter": {},
      "regularPath": "/backend/kafka.html",
      "relativePath": "backend/kafka.md",
      "key": "v-0aa6768e",
      "path": "/backend/kafka.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "相关命令",
          "slug": "相关命令"
        }
      ]
    },
    {
      "title": "LogBack日志配置",
      "frontmatter": {},
      "regularPath": "/backend/logback.html",
      "relativePath": "backend/logback.md",
      "key": "v-27daf3ee",
      "path": "/backend/logback.html"
    },
    {
      "title": "Oracle CDC调研比较",
      "frontmatter": {},
      "regularPath": "/backend/oraclecdc.html",
      "relativePath": "backend/oraclecdc.md",
      "key": "v-1981de4e",
      "path": "/backend/oraclecdc.html"
    },
    {
      "title": "常遇到的问题",
      "frontmatter": {},
      "regularPath": "/backend/problem.html",
      "relativePath": "backend/problem.md",
      "key": "v-a394ff24",
      "path": "/backend/problem.html",
      "headers": [
        {
          "level": 2,
          "title": "Mybatis将0识别成null",
          "slug": "mybatis将0识别成null"
        },
        {
          "level": 2,
          "title": "URLEncode将空格转换为+号问题",
          "slug": "urlencode将空格转换为-号问题"
        },
        {
          "level": 2,
          "title": "各种各样版本问题",
          "slug": "各种各样版本问题"
        }
      ]
    },
    {
      "title": "SpringBoot",
      "frontmatter": {},
      "regularPath": "/backend/springboot.html",
      "relativePath": "backend/springboot.md",
      "key": "v-12ef48a6",
      "path": "/backend/springboot.html",
      "headers": [
        {
          "level": 2,
          "title": "Apsect",
          "slug": "apsect"
        }
      ]
    },
    {
      "title": "Treadpool项目中应用",
      "frontmatter": {},
      "regularPath": "/backend/threadpool.html",
      "relativePath": "backend/threadpool.md",
      "key": "v-00dfb950",
      "path": "/backend/threadpool.html",
      "headers": [
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "等待sumbit结果",
          "slug": "等待sumbit结果"
        },
        {
          "level": 2,
          "title": "CountDownLatch封装",
          "slug": "countdownlatch封装"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-c7034c3a",
      "path": "/config.html"
    },
    {
      "title": "Nvm管理Node版本",
      "frontmatter": {},
      "regularPath": "/front/nvm.html",
      "relativePath": "front/nvm.md",
      "key": "v-46faea64",
      "path": "/front/nvm.html",
      "headers": [
        {
          "level": 2,
          "title": "windows安装nvm",
          "slug": "windows安装nvm"
        },
        {
          "level": 2,
          "title": "nvm命令",
          "slug": "nvm命令"
        },
        {
          "level": 2,
          "title": "环境变量设置",
          "slug": "环境变量设置"
        }
      ]
    },
    {
      "title": "Vue知识",
      "frontmatter": {},
      "regularPath": "/front/vue.html",
      "relativePath": "front/vue.md",
      "key": "v-2e5c8da4",
      "path": "/front/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "组件版本",
          "slug": "组件版本"
        },
        {
          "level": 2,
          "title": "项目搭建",
          "slug": "项目搭建"
        },
        {
          "level": 3,
          "title": "1.创建项目",
          "slug": "_1-创建项目"
        },
        {
          "level": 3,
          "title": "2.集成vue-router",
          "slug": "_2-集成vue-router"
        },
        {
          "level": 3,
          "title": "2.集成element-ui",
          "slug": "_2-集成element-ui"
        },
        {
          "level": 3,
          "title": "3.集成axios",
          "slug": "_3-集成axios"
        },
        {
          "level": 3,
          "title": "4.集成vuex",
          "slug": "_4-集成vuex"
        },
        {
          "level": 3,
          "title": "5.集成svg",
          "slug": "_5-集成svg"
        },
        {
          "level": 3,
          "title": "6.集成scss",
          "slug": "_6-集成scss"
        },
        {
          "level": 3,
          "title": "demo项目",
          "slug": "demo项目"
        },
        {
          "level": 3,
          "title": "命令",
          "slug": "命令"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-8f08771a",
      "path": "/guide/"
    },
    {
      "title": "Author",
      "frontmatter": {},
      "regularPath": "/other/author.html",
      "relativePath": "other/author.md",
      "key": "v-0a0f7046",
      "path": "/other/author.html"
    },
    {
      "title": "GitBook",
      "frontmatter": {},
      "regularPath": "/yunwei/gitbook.html",
      "relativePath": "yunwei/gitbook.md",
      "key": "v-a40fef2c",
      "path": "/yunwei/gitbook.html",
      "headers": [
        {
          "level": 2,
          "title": "说明",
          "slug": "说明"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "插件使用",
          "slug": "插件使用"
        }
      ]
    },
    {
      "title": "GitLab",
      "frontmatter": {},
      "regularPath": "/yunwei/gitlab.html",
      "relativePath": "yunwei/gitlab.md",
      "key": "v-6fbec270",
      "path": "/yunwei/gitlab.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "相关操作",
          "slug": "相关操作"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        }
      ]
    },
    {
      "title": "Jenkins",
      "frontmatter": {},
      "regularPath": "/yunwei/jenkins.html",
      "relativePath": "yunwei/jenkins.md",
      "key": "v-6420fcf4",
      "path": "/yunwei/jenkins.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "工作流程",
          "slug": "工作流程"
        },
        {
          "level": 2,
          "title": "配置步骤",
          "slug": "配置步骤"
        },
        {
          "level": 3,
          "title": "1. 步骤",
          "slug": "_1-步骤"
        },
        {
          "level": 3,
          "title": "2. start.sh",
          "slug": "_2-start-sh"
        },
        {
          "level": 3,
          "title": "3.jenkins全局配置",
          "slug": "_3-jenkins全局配置"
        },
        {
          "level": 2,
          "title": "角色分配",
          "slug": "角色分配"
        },
        {
          "level": 2,
          "title": "使用webhook自动部署",
          "slug": "使用webhook自动部署"
        },
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/yunwei/linux.html",
      "relativePath": "yunwei/linux.md",
      "key": "v-6a1f84f8",
      "path": "/yunwei/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "磁盘相关",
          "slug": "磁盘相关"
        },
        {
          "level": 3,
          "title": "查看日志相关",
          "slug": "查看日志相关"
        },
        {
          "level": 3,
          "title": "压缩解压",
          "slug": "压缩解压"
        },
        {
          "level": 3,
          "title": "软链接",
          "slug": "软链接"
        },
        {
          "level": 3,
          "title": "只保留最近几个任务",
          "slug": "只保留最近几个任务"
        },
        {
          "level": 3,
          "title": "内核版本",
          "slug": "内核版本"
        },
        {
          "level": 2,
          "title": "Crontab定时任务",
          "slug": "crontab定时任务"
        },
        {
          "level": 2,
          "title": "常用脚本",
          "slug": "常用脚本"
        }
      ]
    },
    {
      "title": "Nginx",
      "frontmatter": {},
      "regularPath": "/yunwei/nginx.html",
      "relativePath": "yunwei/nginx.md",
      "key": "v-8f31c9a8",
      "path": "/yunwei/nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "常用conf",
          "slug": "常用conf"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        },
        {
          "level": 2,
          "title": "nginx+lvs 双机主备",
          "slug": "nginx-lvs-双机主备"
        },
        {
          "level": 3,
          "title": "安装keepalived",
          "slug": "安装keepalived"
        },
        {
          "level": 3,
          "title": "keepalived.conf master配置",
          "slug": "keepalived-conf-master配置"
        },
        {
          "level": 3,
          "title": "keepalived.conf",
          "slug": "keepalived-conf"
        },
        {
          "level": 3,
          "title": "命令",
          "slug": "命令-2"
        },
        {
          "level": 3,
          "title": "注册到服务",
          "slug": "注册到服务"
        },
        {
          "level": 3,
          "title": "自动重启",
          "slug": "自动重启"
        }
      ]
    },
    {
      "title": "Prometheus",
      "frontmatter": {},
      "regularPath": "/yunwei/prometheus.html",
      "relativePath": "yunwei/prometheus.md",
      "key": "v-5be93ce8",
      "path": "/yunwei/prometheus.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "集成 Grafana",
          "slug": "集成-grafana"
        },
        {
          "level": 2,
          "title": "Springboot 整合",
          "slug": "springboot-整合"
        }
      ]
    },
    {
      "title": "RabbitMq",
      "frontmatter": {},
      "regularPath": "/yunwei/rabbitmq.html",
      "relativePath": "yunwei/rabbitmq.md",
      "key": "v-2daee668",
      "path": "/yunwei/rabbitmq.html",
      "headers": [
        {
          "level": 2,
          "title": "镜像集群搭建",
          "slug": "镜像集群搭建"
        }
      ]
    },
    {
      "title": "Redis",
      "frontmatter": {},
      "regularPath": "/yunwei/redis.html",
      "relativePath": "yunwei/redis.md",
      "key": "v-47ff02aa",
      "path": "/yunwei/redis.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "主从搭建",
          "slug": "主从搭建"
        },
        {
          "level": 2,
          "title": "哨兵搭建",
          "slug": "哨兵搭建"
        },
        {
          "level": 2,
          "title": "集群搭建",
          "slug": "集群搭建"
        },
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "数据结构",
          "slug": "数据结构"
        },
        {
          "level": 3,
          "title": "基本的五个",
          "slug": "基本的五个"
        },
        {
          "level": 3,
          "title": "复杂的",
          "slug": "复杂的"
        },
        {
          "level": 2,
          "title": "持久化",
          "slug": "持久化"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        }
      ]
    },
    {
      "title": "SuperVisor",
      "frontmatter": {},
      "regularPath": "/yunwei/supervisor.html",
      "relativePath": "yunwei/supervisor.md",
      "key": "v-d7104bb0",
      "path": "/yunwei/supervisor.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置supervisord.conf",
          "slug": "配置supervisord-conf"
        },
        {
          "level": 2,
          "title": "配置项目",
          "slug": "配置项目"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        }
      ]
    },
    {
      "title": "Vim",
      "frontmatter": {},
      "regularPath": "/yunwei/vim.html",
      "relativePath": "yunwei/vim.md",
      "key": "v-348b7fa8",
      "path": "/yunwei/vim.html",
      "headers": [
        {
          "level": 2,
          "title": "配置~/.vimrc",
          "slug": "配置-vimrc"
        },
        {
          "level": 2,
          "title": "底线命令",
          "slug": "底线命令"
        },
        {
          "level": 2,
          "title": "命令模式",
          "slug": "命令模式"
        }
      ]
    },
    {
      "title": "VMware",
      "frontmatter": {},
      "regularPath": "/yunwei/vmware.html",
      "relativePath": "yunwei/vmware.md",
      "key": "v-14e159a8",
      "path": "/yunwei/vmware.html",
      "headers": [
        {
          "level": 2,
          "title": "1.安装",
          "slug": "_1-安装"
        },
        {
          "level": 2,
          "title": "2.配置网络",
          "slug": "_2-配置网络"
        },
        {
          "level": 2,
          "title": "3.一些常用包，vim ssh jdk配置",
          "slug": "_3-一些常用包-vim-ssh-jdk配置"
        },
        {
          "level": 2,
          "title": "4.修改hostname",
          "slug": "_4-修改hostname"
        },
        {
          "level": 2,
          "title": "5.克隆虚拟机",
          "slug": "_5-克隆虚拟机"
        },
        {
          "level": 2,
          "title": "6.ssh-id-copy",
          "slug": "_6-ssh-id-copy"
        }
      ]
    },
    {
      "title": "一次被sshd恶意挖矿的经历",
      "frontmatter": {},
      "regularPath": "/yunwei/wakuang.html",
      "relativePath": "yunwei/wakuang.md",
      "key": "v-038111d8",
      "path": "/yunwei/wakuang.html",
      "headers": [
        {
          "level": 2,
          "title": "过程",
          "slug": "过程"
        },
        {
          "level": 2,
          "title": "处理",
          "slug": "处理"
        },
        {
          "level": 2,
          "title": "观察",
          "slug": "观察"
        }
      ]
    },
    {
      "title": "Confluence Wiki",
      "frontmatter": {},
      "regularPath": "/yunwei/wiki.html",
      "relativePath": "yunwei/wiki.md",
      "key": "v-da2006b0",
      "path": "/yunwei/wiki.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建",
          "slug": "搭建"
        },
        {
          "level": 2,
          "title": "备份",
          "slug": "备份"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "nav": [
      {
        "text": "数据结构",
        "link": "https://shanyuguangyun.github.io/dsBook"
      },
      {
        "text": "基础知识",
        "link": "https://shanyuguangyun.github.io/gitBook"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/shanyuguangyun"
      }
    ],
    "sidebar": [
      {
        "title": "前端",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/front/vue",
          "/front/nvm"
        ]
      },
      {
        "title": "后端",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/backend/springboot",
          "/backend/threadpool",
          "/backend/logback",
          "/backend/easyexcel",
          "/backend/fdfs",
          "/backend/hadoop",
          "/backend/elasticsearch",
          "/backend/canal",
          "/backend/oraclecdc",
          "/backend/flinkcdc",
          "/backend/kafka",
          "/backend/arthas",
          "/backend/intelij",
          "/backend/problem"
        ]
      },
      {
        "title": "运维手册",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/yunwei/vmware",
          "/yunwei/nginx",
          "/yunwei/linux",
          "/yunwei/vim",
          "/yunwei/supervisor",
          "/yunwei/gitbook",
          "/yunwei/gitlab",
          "/yunwei/jenkins",
          "/yunwei/redis",
          "/yunwei/prometheus",
          "/yunwei/rabbitmq",
          "/yunwei/wiki",
          "/yunwei/wakuang"
        ]
      },
      {
        "title": "其他",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/other/author"
        ]
      }
    ]
  }
}