/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小冯的Web手册",
  "description": "小冯的Web手册",
  "base": "/webBook/",
  "headTags": [],
  "pages": [
    {
      "title": "SpringBoot",
      "frontmatter": {},
      "regularPath": "/backend/springboot.html",
      "relativePath": "backend/springboot.md",
      "key": "v-12ef48a6",
      "path": "/backend/springboot.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/work.png",
        "heroText": "小冯的Web笔记",
        "tagline": "前后端、运维技术手册",
        "actionText": "打开笔记 →",
        "actionLink": "/front/html",
        "features": [
          {
            "title": "前端",
            "details": "Html、Css、JavaScript、Vue相关技术栈"
          },
          {
            "title": "后端",
            "details": "Java、SpringBoot、SpringCloud、Mysql、Redis等相关技术栈，尤其擅长多线程相关技术"
          },
          {
            "title": "运维",
            "details": "包含Gitlab、Jenkins、FDFS、Nginx等基础服务搭建及脚本"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-a94b7e40",
      "path": "/"
    },
    {
      "title": "Treadpool项目中应用",
      "frontmatter": {},
      "regularPath": "/backend/threadpool.html",
      "relativePath": "backend/threadpool.md",
      "key": "v-00dfb950",
      "path": "/backend/threadpool.html",
      "headers": [
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "等待sumbit结果",
          "slug": "等待sumbit结果"
        },
        {
          "level": 2,
          "title": "CountDownLatch封装",
          "slug": "countdownlatch封装"
        }
      ]
    },
    {
      "title": "CSS相关",
      "frontmatter": {},
      "regularPath": "/front/css.html",
      "relativePath": "front/css.md",
      "key": "v-61e63a0e",
      "path": "/front/css.html",
      "headers": [
        {
          "level": 2,
          "title": "奇怪的样式",
          "slug": "奇怪的样式"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-c7034c3a",
      "path": "/config.html"
    },
    {
      "title": "HTML相关",
      "frontmatter": {},
      "regularPath": "/front/html.html",
      "relativePath": "front/html.md",
      "key": "v-d758d610",
      "path": "/front/html.html",
      "headers": [
        {
          "level": 2,
          "title": "不常用标签",
          "slug": "不常用标签"
        }
      ]
    },
    {
      "title": "Nvm管理Node版本",
      "frontmatter": {},
      "regularPath": "/front/nvm.html",
      "relativePath": "front/nvm.md",
      "key": "v-46faea64",
      "path": "/front/nvm.html",
      "headers": [
        {
          "level": 2,
          "title": "windows安装nvm",
          "slug": "windows安装nvm"
        },
        {
          "level": 2,
          "title": "nvm命令",
          "slug": "nvm命令"
        },
        {
          "level": 2,
          "title": "环境变量设置",
          "slug": "环境变量设置"
        }
      ]
    },
    {
      "title": "Vue知识",
      "frontmatter": {},
      "regularPath": "/front/vue.html",
      "relativePath": "front/vue.md",
      "key": "v-2e5c8da4",
      "path": "/front/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建项目",
          "slug": "搭建项目"
        },
        {
          "level": 3,
          "title": "版本使用",
          "slug": "版本使用"
        }
      ]
    },
    {
      "title": "GitBook",
      "frontmatter": {},
      "regularPath": "/yunwei/gitbook.html",
      "relativePath": "yunwei/gitbook.md",
      "key": "v-a40fef2c",
      "path": "/yunwei/gitbook.html",
      "headers": [
        {
          "level": 2,
          "title": "说明",
          "slug": "说明"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "插件使用",
          "slug": "插件使用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-8f08771a",
      "path": "/guide/"
    },
    {
      "title": "GitLab",
      "frontmatter": {},
      "regularPath": "/yunwei/gitlab.html",
      "relativePath": "yunwei/gitlab.md",
      "key": "v-6fbec270",
      "path": "/yunwei/gitlab.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "相关操作",
          "slug": "相关操作"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        }
      ]
    },
    {
      "title": "Jenkins",
      "frontmatter": {},
      "regularPath": "/yunwei/jenkins.html",
      "relativePath": "yunwei/jenkins.md",
      "key": "v-6420fcf4",
      "path": "/yunwei/jenkins.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "工作流程",
          "slug": "工作流程"
        },
        {
          "level": 2,
          "title": "配置步骤",
          "slug": "配置步骤"
        },
        {
          "level": 3,
          "title": "1. 步骤",
          "slug": "_1-步骤"
        },
        {
          "level": 3,
          "title": "2. start.sh",
          "slug": "_2-start-sh"
        },
        {
          "level": 3,
          "title": "3.jenkins全局配置",
          "slug": "_3-jenkins全局配置"
        },
        {
          "level": 2,
          "title": "角色分配",
          "slug": "角色分配"
        },
        {
          "level": 2,
          "title": "使用webhook自动部署",
          "slug": "使用webhook自动部署"
        },
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        }
      ]
    },
    {
      "title": "EasyExcel使用",
      "frontmatter": {},
      "regularPath": "/backend/easyexcel.html",
      "relativePath": "backend/easyexcel.md",
      "key": "v-46789dae",
      "path": "/backend/easyexcel.html",
      "headers": [
        {
          "level": 2,
          "title": "导出复杂表头",
          "slug": "导出复杂表头"
        },
        {
          "level": 2,
          "title": "最后使用合计行",
          "slug": "最后使用合计行"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/yunwei/linux.html",
      "relativePath": "yunwei/linux.md",
      "key": "v-6a1f84f8",
      "path": "/yunwei/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "磁盘相关",
          "slug": "磁盘相关"
        },
        {
          "level": 3,
          "title": "查看日志相关",
          "slug": "查看日志相关"
        },
        {
          "level": 3,
          "title": "压缩解压",
          "slug": "压缩解压"
        },
        {
          "level": 2,
          "title": "Crontab定时任务",
          "slug": "crontab定时任务"
        },
        {
          "level": 2,
          "title": "常用脚本",
          "slug": "常用脚本"
        }
      ]
    },
    {
      "title": "LogBack日志配置",
      "frontmatter": {},
      "regularPath": "/backend/logback.html",
      "relativePath": "backend/logback.md",
      "key": "v-27daf3ee",
      "path": "/backend/logback.html"
    },
    {
      "title": "RabbitMq",
      "frontmatter": {},
      "regularPath": "/yunwei/rabbitmq.html",
      "relativePath": "yunwei/rabbitmq.md",
      "key": "v-2daee668",
      "path": "/yunwei/rabbitmq.html",
      "headers": [
        {
          "level": 2,
          "title": "镜像集群搭建",
          "slug": "镜像集群搭建"
        }
      ]
    },
    {
      "title": "SuperVisor",
      "frontmatter": {},
      "regularPath": "/yunwei/supervisor.html",
      "relativePath": "yunwei/supervisor.md",
      "key": "v-d7104bb0",
      "path": "/yunwei/supervisor.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "配置supervisord.conf",
          "slug": "配置supervisord-conf"
        },
        {
          "level": 2,
          "title": "配置项目",
          "slug": "配置项目"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        }
      ]
    },
    {
      "title": "Nginx",
      "frontmatter": {},
      "regularPath": "/yunwei/nginx.html",
      "relativePath": "yunwei/nginx.md",
      "key": "v-8f31c9a8",
      "path": "/yunwei/nginx.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "常用conf",
          "slug": "常用conf"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        },
        {
          "level": 2,
          "title": "常见问题",
          "slug": "常见问题"
        },
        {
          "level": 2,
          "title": "nginx+lvs 双机主备",
          "slug": "nginx-lvs-双机主备"
        },
        {
          "level": 3,
          "title": "安装keepalived",
          "slug": "安装keepalived"
        },
        {
          "level": 3,
          "title": "keepalived.conf master配置",
          "slug": "keepalived-conf-master配置"
        },
        {
          "level": 3,
          "title": "keepalived.conf",
          "slug": "keepalived-conf"
        },
        {
          "level": 3,
          "title": "命令",
          "slug": "命令-2"
        },
        {
          "level": 3,
          "title": "注册到服务",
          "slug": "注册到服务"
        },
        {
          "level": 3,
          "title": "自动重启",
          "slug": "自动重启"
        }
      ]
    },
    {
      "title": "Redis",
      "frontmatter": {},
      "regularPath": "/yunwei/redis.html",
      "relativePath": "yunwei/redis.md",
      "key": "v-47ff02aa",
      "path": "/yunwei/redis.html",
      "headers": [
        {
          "level": 2,
          "title": "主从搭建",
          "slug": "主从搭建"
        },
        {
          "level": 2,
          "title": "哨兵搭建",
          "slug": "哨兵搭建"
        },
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        }
      ]
    },
    {
      "title": "FDFS使用",
      "frontmatter": {},
      "regularPath": "/backend/fdfs.html",
      "relativePath": "backend/fdfs.md",
      "key": "v-11fa958e",
      "path": "/backend/fdfs.html",
      "headers": [
        {
          "level": 2,
          "title": "是什么",
          "slug": "是什么"
        },
        {
          "level": 2,
          "title": "FDFS搭建",
          "slug": "fdfs搭建"
        },
        {
          "level": 2,
          "title": "FDFS使用",
          "slug": "fdfs使用-2"
        }
      ]
    },
    {
      "title": "Confluence Wiki",
      "frontmatter": {},
      "regularPath": "/yunwei/wiki.html",
      "relativePath": "yunwei/wiki.md",
      "key": "v-da2006b0",
      "path": "/yunwei/wiki.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建",
          "slug": "搭建"
        },
        {
          "level": 2,
          "title": "备份",
          "slug": "备份"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "sidebar": [
      {
        "title": "前端",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/front/html",
          "/front/css",
          "/front/vue",
          "/front/nvm"
        ]
      },
      {
        "title": "后端",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/backend/springboot",
          "/backend/threadpool",
          "/backend/logback",
          "/backend/easyexcel",
          "/backend/fdfs"
        ]
      },
      {
        "title": "运维手册",
        "collapsable": false,
        "sidebarDepth": 2,
        "children": [
          "/yunwei/nginx",
          "/yunwei/linux",
          "/yunwei/supervisor",
          "/yunwei/rabbitmq",
          "/yunwei/gitbook",
          "/yunwei/gitlab",
          "/yunwei/jenkins",
          "/yunwei/wiki",
          "/yunwei/redis"
        ]
      }
    ]
  }
}