/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小冯的Web手册",
  "description": "小冯的Web手册",
  "base": "/webBook/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/work.png",
        "heroText": "小冯的Web笔记",
        "tagline": "前后端、运维技术手册",
        "actionText": "打开笔记 →",
        "actionLink": "/front/html",
        "features": [
          {
            "title": "前端",
            "details": "Html、Css、JavaScript、Vue相关技术栈"
          },
          {
            "title": "后端",
            "details": "Java、SpringBoot、SpringCloud、Mysql、Redis等相关技术栈，尤其擅长多线程相关技术"
          },
          {
            "title": "运维",
            "details": "包含Gitlab、Jenkins、FDFS、Nginx等基础服务搭建及脚本"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-37bad3a1",
      "path": "/"
    },
    {
      "title": "SpringBoot",
      "frontmatter": {},
      "regularPath": "/backend/springboot.html",
      "relativePath": "backend/springboot.md",
      "key": "v-47421376",
      "path": "/backend/springboot.html"
    },
    {
      "title": "CSS相关",
      "frontmatter": {},
      "regularPath": "/front/css.html",
      "relativePath": "front/css.md",
      "key": "v-f3113d26",
      "path": "/front/css.html",
      "headers": [
        {
          "level": 2,
          "title": "奇怪的样式",
          "slug": "奇怪的样式"
        }
      ]
    },
    {
      "title": "Vue知识",
      "frontmatter": {},
      "regularPath": "/front/vue.html",
      "relativePath": "front/vue.md",
      "key": "v-0d62e08d",
      "path": "/front/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "搭建项目",
          "slug": "搭建项目"
        },
        {
          "level": 3,
          "title": "版本使用",
          "slug": "版本使用"
        }
      ]
    },
    {
      "title": "HTML相关",
      "frontmatter": {},
      "regularPath": "/front/html.html",
      "relativePath": "front/html.md",
      "key": "v-4d8f3ed2",
      "path": "/front/html.html",
      "headers": [
        {
          "level": 2,
          "title": "不常用标签",
          "slug": "不常用标签"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-9d4796fc",
      "path": "/config.html"
    },
    {
      "title": "nvm管理Node版本",
      "frontmatter": {},
      "regularPath": "/front/nvm.html",
      "relativePath": "front/nvm.md",
      "key": "v-0113b22d",
      "path": "/front/nvm.html",
      "headers": [
        {
          "level": 2,
          "title": "windows安装nvm",
          "slug": "windows安装nvm"
        },
        {
          "level": 2,
          "title": "nvm命令",
          "slug": "nvm命令"
        }
      ]
    },
    {
      "title": "Linux",
      "frontmatter": {},
      "regularPath": "/yunwei/linux.html",
      "relativePath": "yunwei/linux.md",
      "key": "v-5b312dd2",
      "path": "/yunwei/linux.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "工作相关查看日志",
          "slug": "工作相关查看日志"
        },
        {
          "level": 2,
          "title": "Corntab定时任务",
          "slug": "corntab定时任务"
        },
        {
          "level": 2,
          "title": "常用脚本",
          "slug": "常用脚本"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-3f593db4",
      "path": "/guide/"
    },
    {
      "title": "Nginx",
      "frontmatter": {},
      "regularPath": "/yunwei/nginx.html",
      "relativePath": "yunwei/nginx.md",
      "key": "v-20aeff4b",
      "path": "/yunwei/nginx.html"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 3,
    "sidebar": [
      {
        "title": "前端",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/front/html",
          "/front/css",
          "/front/vue",
          "/front/nvm"
        ]
      },
      {
        "title": "后端",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/backend/springboot"
        ]
      },
      {
        "title": "运维手册",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/yunwei/nginx",
          "/yunwei/linux"
        ]
      }
    ]
  }
}